# Generated by Django 5.1.7 on 2025-03-28 04:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('fruits', 'Fruits'), ('vegetables', 'Vegetables'), ('herbs', 'Herbs & Greens'), ('microgreens', 'Microgreens'), ('seasonal', 'Seasonal Produce'), ('organic', 'Organic Produce')], default='organic', max_length=20),
        ),
        migrations.AddField(
            model_name='item',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='item',
            name='image_url',
            field=models.CharField(default='https://developers.elementor.com/path/to/placeholder.png', max_length=255),
        ),
        migrations.AddField(
            model_name='item',
            name='labels',
            field=models.CharField(blank=True, choices=[('organic', 'Organic'), ('vegan', 'Vegan'), ('locally_sourced', 'Locally Sourced'), ('freshly_harvested', 'Freshly Harvested'), ('seasonal', 'Seasonal Produce'), ('farm_fresh', 'Farm Fresh'), ('sustainably_farmed', 'Sustainably Farmed'), ('zero_waste', 'Zero-Waste Packaging')], max_length=20),
        ),
        migrations.AddField(
            model_name='item',
            name='stock',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='is_ordered',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
