# Generated by Django 5.1.7 on 2025-03-29 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_item_slug_alter_order_ordered_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='carbon_footprint',
            field=models.PositiveIntegerField(blank=True, default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='farm_location',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
