# Generated by Django 5.1.7 on 2025-04-04 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='tracking_no',
            field=models.CharField(default='XXX-XXX-XXX', max_length=150, null=True),
        ),
    ]
