# Generated by Django 5.1.7 on 2025-04-04 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_order_tracking_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='name',
        ),
    ]
