# Generated by Django 5.1.7 on 2025-04-04 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_remove_order_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='slug',
            field=models.SlugField(default='test-order', unique=True),
        ),
    ]
