# Generated by Django 5.1.7 on 2025-04-05 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_order_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='order_id',
            field=models.CharField(default='XXX', max_length=150, null=True),
        ),
    ]
