# Generated by Django 5.1.7 on 2025-04-05 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_address_order_address_payment_order_payment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='delivery_address',
        ),
        migrations.AlterField(
            model_name='order',
            name='slug',
            field=models.SlugField(default='order', unique=True),
        ),
    ]
