# Generated by Django 5.1.7 on 2025-04-05 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_remove_order_delivery_address_alter_order_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='tracking_no',
            field=models.CharField(default='YLE-4RC-V48', max_length=150, null=True),
        ),
    ]
