# Generated by Django 5.1.7 on 2025-04-06 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_alter_order_tracking_no_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='tracking_no',
            field=models.CharField(default='87W-TCN-DIF', max_length=150, null=True),
        ),
    ]
