# Generated by Django 5.1.7 on 2025-04-06 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_alter_order_tracking_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='tracking_no',
            field=models.CharField(default='IU9-K3P-SAH', max_length=150, null=True),
        ),
    ]
