# Generated by Django 5.1.7 on 2025-04-13 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_promotion_alter_order_tracking_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotion',
            name='discount_rate',
            field=models.DecimalField(decimal_places=2, default=10, help_text='Enter as a percentage (e.g. 10.00 for 10%)', max_digits=5),
        ),
        migrations.AlterField(
            model_name='order',
            name='tracking_no',
            field=models.CharField(default='TJX-8Z8-BOC', max_length=150, null=True),
        ),
    ]
