# Generated by Django 5.1.7 on 2025-04-13 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_alter_item_carbon_footprint_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='tracking_no',
            field=models.CharField(default='1K9-NQJ-ZSL', max_length=150, null=True),
        ),
    ]
