# Generated by Django 5.1.7 on 2025-04-13 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_order_discount_amount_order_final_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='tracking_no',
            field=models.CharField(default='QZV-KEZ-83N', max_length=150, null=True),
        ),
    ]
