# Generated by Django 5.1.7 on 2025-04-13 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_item_discounted_price_alter_order_tracking_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='discounted_price',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='discounted_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='tracking_no',
            field=models.CharField(default='C0V-EJ6-ZHN', max_length=150, null=True),
        ),
    ]
