# Generated by Django 5.1.7 on 2025-04-14 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_userprofile_city_userprofile_postal_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='tracking_no',
            field=models.CharField(default='UBE-97J-KO2', max_length=150, null=True),
        ),
    ]
