# Generated by Django 5.1.7 on 2025-04-14 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_alter_order_tracking_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='tracking_no',
            field=models.CharField(default='NU9-GRN-Y4L', max_length=150, null=True),
        ),
    ]
